<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('municipios')->insertOrIgnore([
            // AHUACHAPÁN (dep 1)
            ['id' => 2,   'departamento_id' => 1,  'nombre' => 'AHUACHAPÁN',                  'activo' => true],
            ['id' => 3,   'departamento_id' => 1,  'nombre' => 'JUJUTLA',                     'activo' => true],
            ['id' => 4,   'departamento_id' => 1,  'nombre' => 'ATIQUIZAYA',                  'activo' => true],
            ['id' => 5,   'departamento_id' => 1,  'nombre' => 'CONCEPCIÓN DE ATACO',         'activo' => true],
            ['id' => 6,   'departamento_id' => 1,  'nombre' => 'EL REFUGIO',                  'activo' => true],
            ['id' => 7,   'departamento_id' => 1,  'nombre' => 'GUAYMANGO',                   'activo' => true],
            ['id' => 8,   'departamento_id' => 1,  'nombre' => 'APANECA',                     'activo' => true],
            ['id' => 9,   'departamento_id' => 1,  'nombre' => 'SAN FRANCISCO MENÉNDEZ',      'activo' => true],
            ['id' => 10,  'departamento_id' => 1,  'nombre' => 'SAN LORENZO',                 'activo' => true],
            ['id' => 11,  'departamento_id' => 1,  'nombre' => 'SAN PEDRO PUXTLA',            'activo' => true],
            ['id' => 12,  'departamento_id' => 1,  'nombre' => 'TACUBA',                      'activo' => true],
            ['id' => 13,  'departamento_id' => 1,  'nombre' => 'TURÍN',                       'activo' => true],
            // SANTA ANA (dep 2)
            ['id' => 14,  'departamento_id' => 2,  'nombre' => 'CANDELARIA DE LA FRONTERA',   'activo' => true],
            ['id' => 15,  'departamento_id' => 2,  'nombre' => 'CHALCHUAPA',                  'activo' => true],
            ['id' => 16,  'departamento_id' => 2,  'nombre' => 'COATEPEQUE',                  'activo' => true],
            ['id' => 17,  'departamento_id' => 2,  'nombre' => 'EL CONGO',                    'activo' => true],
            ['id' => 18,  'departamento_id' => 2,  'nombre' => 'EL PORVENIR',                 'activo' => true],
            ['id' => 19,  'departamento_id' => 2,  'nombre' => 'MASAHUAT',                    'activo' => true],
            ['id' => 20,  'departamento_id' => 2,  'nombre' => 'METAPÁN',                     'activo' => true],
            ['id' => 21,  'departamento_id' => 2,  'nombre' => 'SAN ANTONIO PAJONAL',         'activo' => true],
            ['id' => 22,  'departamento_id' => 2,  'nombre' => 'SAN SEBASTIÁN SALITRILLO',    'activo' => true],
            ['id' => 23,  'departamento_id' => 2,  'nombre' => 'SANTA ANA',                   'activo' => true],
            ['id' => 24,  'departamento_id' => 2,  'nombre' => 'SANTA ROSA GUACHIPILÍN',      'activo' => true],
            ['id' => 25,  'departamento_id' => 2,  'nombre' => 'SANTIAGO DE LA FRONTERA',     'activo' => true],
            ['id' => 26,  'departamento_id' => 2,  'nombre' => 'TEXISTEPEQUE',                'activo' => true],
            // SONSONATE (dep 3)
            ['id' => 27,  'departamento_id' => 3,  'nombre' => 'ACAJUTLA',                    'activo' => true],
            ['id' => 28,  'departamento_id' => 3,  'nombre' => 'ARMENIA',                     'activo' => true],
            ['id' => 29,  'departamento_id' => 3,  'nombre' => 'CALUCO',                      'activo' => true],
            ['id' => 30,  'departamento_id' => 3,  'nombre' => 'CUISNAHUAT',                  'activo' => true],
            ['id' => 31,  'departamento_id' => 3,  'nombre' => 'IZALCO',                      'activo' => true],
            ['id' => 32,  'departamento_id' => 3,  'nombre' => 'JUAYÚA',                      'activo' => true],
            ['id' => 33,  'departamento_id' => 3,  'nombre' => 'NAHUIZALCO',                  'activo' => true],
            ['id' => 34,  'departamento_id' => 3,  'nombre' => 'NAHULINGO',                   'activo' => true],
            ['id' => 35,  'departamento_id' => 3,  'nombre' => 'SALCOATITÁN',                 'activo' => true],
            ['id' => 36,  'departamento_id' => 3,  'nombre' => 'SAN ANTONIO DEL MONTE',       'activo' => true],
            ['id' => 37,  'departamento_id' => 3,  'nombre' => 'SAN JULIÁN',                  'activo' => true],
            ['id' => 38,  'departamento_id' => 3,  'nombre' => 'SANTA CATARINA MASAHUAT',     'activo' => true],
            ['id' => 39,  'departamento_id' => 3,  'nombre' => 'SANTA ISABEL ISHUATÁN',       'activo' => true],
            ['id' => 40,  'departamento_id' => 3,  'nombre' => 'SANTO DOMINGO DE GUZMÁN',     'activo' => true],
            ['id' => 41,  'departamento_id' => 3,  'nombre' => 'SONSONATE',                   'activo' => true],
            ['id' => 42,  'departamento_id' => 3,  'nombre' => 'SONZACATE',                   'activo' => true],
            // USULUTÁN (dep 4)
            ['id' => 43,  'departamento_id' => 4,  'nombre' => 'ALEGRÍA',                     'activo' => true],
            ['id' => 44,  'departamento_id' => 4,  'nombre' => 'BERLÍN',                      'activo' => true],
            ['id' => 45,  'departamento_id' => 4,  'nombre' => 'CALIFORNIA',                  'activo' => true],
            ['id' => 46,  'departamento_id' => 4,  'nombre' => 'CONCEPCIÓN BATRES',           'activo' => true],
            ['id' => 47,  'departamento_id' => 4,  'nombre' => 'EL TRIUNFO',                  'activo' => true],
            ['id' => 48,  'departamento_id' => 4,  'nombre' => 'EREGUAYQUÍN',                 'activo' => true],
            ['id' => 49,  'departamento_id' => 4,  'nombre' => 'ESTANZUELAS',                 'activo' => true],
            ['id' => 50,  'departamento_id' => 4,  'nombre' => 'JIQUILISCO',                  'activo' => true],
            ['id' => 51,  'departamento_id' => 4,  'nombre' => 'JUCUAPA',                     'activo' => true],
            ['id' => 52,  'departamento_id' => 4,  'nombre' => 'JUCUARÁN',                    'activo' => true],
            ['id' => 53,  'departamento_id' => 4,  'nombre' => 'MERCEDES UMAÑA',              'activo' => true],
            ['id' => 54,  'departamento_id' => 4,  'nombre' => 'NUEVA GRANADA',               'activo' => true],
            ['id' => 55,  'departamento_id' => 4,  'nombre' => 'OZATLÁN',                     'activo' => true],
            ['id' => 56,  'departamento_id' => 4,  'nombre' => 'PUERTO EL TRIUNFO',           'activo' => true],
            ['id' => 57,  'departamento_id' => 4,  'nombre' => 'SAN AGUSTÍN',                 'activo' => true],
            ['id' => 58,  'departamento_id' => 4,  'nombre' => 'SAN BUENAVENTURA',            'activo' => true],
            ['id' => 59,  'departamento_id' => 4,  'nombre' => 'SAN DIONISIO',                'activo' => true],
            ['id' => 60,  'departamento_id' => 4,  'nombre' => 'SAN FRANCISCO JAVIER',        'activo' => true],
            ['id' => 61,  'departamento_id' => 4,  'nombre' => 'SANTA ELENA',                 'activo' => true],
            ['id' => 62,  'departamento_id' => 4,  'nombre' => 'SANTA MARÍA',                 'activo' => true],
            ['id' => 63,  'departamento_id' => 4,  'nombre' => 'SANTIAGO DE MARÍA',           'activo' => true],
            ['id' => 64,  'departamento_id' => 4,  'nombre' => 'TECAPÁN',                     'activo' => true],
            ['id' => 65,  'departamento_id' => 4,  'nombre' => 'USULUTÁN',                    'activo' => true],
            // SAN MIGUEL (dep 5)
            ['id' => 66,  'departamento_id' => 5,  'nombre' => 'CAROLINA',                    'activo' => true],
            ['id' => 67,  'departamento_id' => 5,  'nombre' => 'CHAPELTIQUE',                 'activo' => true],
            ['id' => 68,  'departamento_id' => 5,  'nombre' => 'CHINAMECA',                   'activo' => true],
            ['id' => 69,  'departamento_id' => 5,  'nombre' => 'CHIRILAGUA',                  'activo' => true],
            ['id' => 70,  'departamento_id' => 5,  'nombre' => 'CIUDAD BARRIOS',              'activo' => true],
            ['id' => 71,  'departamento_id' => 5,  'nombre' => 'COMACARÁN',                   'activo' => true],
            ['id' => 72,  'departamento_id' => 5,  'nombre' => 'EL TRÁNSITO',                 'activo' => true],
            ['id' => 73,  'departamento_id' => 5,  'nombre' => 'LOLOTIQUE',                   'activo' => true],
            ['id' => 74,  'departamento_id' => 5,  'nombre' => 'MONCAGUA',                    'activo' => true],
            ['id' => 75,  'departamento_id' => 5,  'nombre' => 'NUEVA GUADALUPE',             'activo' => true],
            ['id' => 76,  'departamento_id' => 5,  'nombre' => 'NUEVO EDÉN DE SAN JUAN',      'activo' => true],
            ['id' => 77,  'departamento_id' => 5,  'nombre' => 'QUELEPA',                     'activo' => true],
            ['id' => 78,  'departamento_id' => 5,  'nombre' => 'SAN ANTONIO',                 'activo' => true],
            ['id' => 79,  'departamento_id' => 5,  'nombre' => 'SAN GERARDO',                 'activo' => true],
            ['id' => 80,  'departamento_id' => 5,  'nombre' => 'SAN JORGE',                   'activo' => true],
            ['id' => 81,  'departamento_id' => 5,  'nombre' => 'SAN LUIS DE LA REINA',        'activo' => true],
            ['id' => 82,  'departamento_id' => 5,  'nombre' => 'SAN MIGUEL',                  'activo' => true],
            ['id' => 83,  'departamento_id' => 5,  'nombre' => 'SAN RAFAEL ORIENTE',          'activo' => true],
            ['id' => 84,  'departamento_id' => 5,  'nombre' => 'SESORI',                      'activo' => true],
            ['id' => 85,  'departamento_id' => 5,  'nombre' => 'ULUAZAPA',                    'activo' => true],
            // MORAZÁN (dep 6)
            ['id' => 86,  'departamento_id' => 6,  'nombre' => 'ARAMBALA',                    'activo' => true],
            ['id' => 87,  'departamento_id' => 6,  'nombre' => 'CACAOPERA',                   'activo' => true],
            ['id' => 88,  'departamento_id' => 6,  'nombre' => 'CHILANGA',                    'activo' => true],
            ['id' => 89,  'departamento_id' => 6,  'nombre' => 'CORINTO',                     'activo' => true],
            ['id' => 90,  'departamento_id' => 6,  'nombre' => 'DELICIAS DE CONCEPCIÓN',      'activo' => true],
            ['id' => 91,  'departamento_id' => 6,  'nombre' => 'EL DIVISADERO',               'activo' => true],
            ['id' => 92,  'departamento_id' => 6,  'nombre' => 'EL ROSARIO',                  'activo' => true],
            ['id' => 93,  'departamento_id' => 6,  'nombre' => 'GUALOCOCTI',                  'activo' => true],
            ['id' => 94,  'departamento_id' => 6,  'nombre' => 'GUATAJIAGUA',                 'activo' => true],
            ['id' => 95,  'departamento_id' => 6,  'nombre' => 'JOATECA',                     'activo' => true],
            ['id' => 96,  'departamento_id' => 6,  'nombre' => 'JOCOAITIQUE',                 'activo' => true],
            ['id' => 97,  'departamento_id' => 6,  'nombre' => 'JOCORO',                      'activo' => true],
            ['id' => 98,  'departamento_id' => 6,  'nombre' => 'LOLOTIQUILLO',                'activo' => true],
            ['id' => 99,  'departamento_id' => 6,  'nombre' => 'MEANGUERA',                   'activo' => true],
            ['id' => 100, 'departamento_id' => 6,  'nombre' => 'OSICALA',                     'activo' => true],
            ['id' => 101, 'departamento_id' => 6,  'nombre' => 'PERQUÍN',                     'activo' => true],
            ['id' => 102, 'departamento_id' => 6,  'nombre' => 'SAN CARLOS',                  'activo' => true],
            ['id' => 103, 'departamento_id' => 6,  'nombre' => 'SAN FERNANDO',                'activo' => true],
            ['id' => 104, 'departamento_id' => 6,  'nombre' => 'SAN FRANCISCO GOTERA',        'activo' => true],
            ['id' => 105, 'departamento_id' => 6,  'nombre' => 'SAN ISIDRO',                  'activo' => true],
            ['id' => 106, 'departamento_id' => 6,  'nombre' => 'SAN SIMÓN',                   'activo' => true],
            ['id' => 107, 'departamento_id' => 6,  'nombre' => 'SENSEMBRA',                   'activo' => true],
            ['id' => 108, 'departamento_id' => 6,  'nombre' => 'SOCIEDAD',                    'activo' => true],
            ['id' => 109, 'departamento_id' => 6,  'nombre' => 'TOROLA',                      'activo' => true],
            ['id' => 110, 'departamento_id' => 6,  'nombre' => 'YAMABAL',                     'activo' => true],
            ['id' => 111, 'departamento_id' => 6,  'nombre' => 'YOLOAIQUÍN',                  'activo' => true],
            // LA UNIÓN (dep 7)
            ['id' => 112, 'departamento_id' => 7,  'nombre' => 'LA UNIÓN',                    'activo' => true],
            ['id' => 113, 'departamento_id' => 7,  'nombre' => 'SAN ALEJO',                   'activo' => true],
            ['id' => 114, 'departamento_id' => 7,  'nombre' => 'YUCUAIQUÍN',                  'activo' => true],
            ['id' => 115, 'departamento_id' => 7,  'nombre' => 'CONCHAGUA',                   'activo' => true],
            ['id' => 116, 'departamento_id' => 7,  'nombre' => 'INTIPUCÁ',                    'activo' => true],
            ['id' => 117, 'departamento_id' => 7,  'nombre' => 'SAN JOSÉ',                    'activo' => true],
            ['id' => 118, 'departamento_id' => 7,  'nombre' => 'EL CARMEN',                   'activo' => true],
            ['id' => 119, 'departamento_id' => 7,  'nombre' => 'YAYANTIQUE',                  'activo' => true],
            ['id' => 120, 'departamento_id' => 7,  'nombre' => 'BOLÍVAR',                     'activo' => true],
            ['id' => 121, 'departamento_id' => 7,  'nombre' => 'MEANGUERA DEL GOLFO',         'activo' => true],
            ['id' => 122, 'departamento_id' => 7,  'nombre' => 'SANTA ROSA DE LIMA',          'activo' => true],
            ['id' => 123, 'departamento_id' => 7,  'nombre' => 'PASAQUINA',                   'activo' => true],
            ['id' => 124, 'departamento_id' => 7,  'nombre' => 'ANAMOROS',                    'activo' => true],
            ['id' => 125, 'departamento_id' => 7,  'nombre' => 'NUEVA ESPARTA',               'activo' => true],
            ['id' => 126, 'departamento_id' => 7,  'nombre' => 'EL SAUCE',                    'activo' => true],
            ['id' => 127, 'departamento_id' => 7,  'nombre' => 'CONCEPCIÓN DE ORIENTE',       'activo' => true],
            ['id' => 128, 'departamento_id' => 7,  'nombre' => 'POLORÓS',                     'activo' => true],
            ['id' => 129, 'departamento_id' => 7,  'nombre' => 'LISLIQUE',                    'activo' => true],
            // LA LIBERTAD (dep 8)
            ['id' => 130, 'departamento_id' => 8,  'nombre' => 'ANTIGUO CUSCATLÁN',           'activo' => true],
            ['id' => 131, 'departamento_id' => 8,  'nombre' => 'CHILTIUPÁN',                  'activo' => true],
            ['id' => 132, 'departamento_id' => 8,  'nombre' => 'CIUDAD ARCE',                 'activo' => true],
            ['id' => 133, 'departamento_id' => 8,  'nombre' => 'COLÓN',                       'activo' => true],
            ['id' => 134, 'departamento_id' => 8,  'nombre' => 'COMASAGUA',                   'activo' => true],
            ['id' => 135, 'departamento_id' => 8,  'nombre' => 'HUIZÚCAR',                    'activo' => true],
            ['id' => 136, 'departamento_id' => 8,  'nombre' => 'JAYAQUE',                     'activo' => true],
            ['id' => 137, 'departamento_id' => 8,  'nombre' => 'JICALAPA',                    'activo' => true],
            ['id' => 138, 'departamento_id' => 8,  'nombre' => 'LA LIBERTAD',                 'activo' => true],
            ['id' => 139, 'departamento_id' => 8,  'nombre' => 'SANTA TECLA',                 'activo' => true],
            ['id' => 140, 'departamento_id' => 8,  'nombre' => 'NUEVO CUSCATLÁN',             'activo' => true],
            ['id' => 141, 'departamento_id' => 8,  'nombre' => 'SAN JUAN OPICO',              'activo' => true],
            ['id' => 142, 'departamento_id' => 8,  'nombre' => 'QUEZALTEPEQUE',               'activo' => true],
            ['id' => 143, 'departamento_id' => 8,  'nombre' => 'SACACOYO',                    'activo' => true],
            ['id' => 144, 'departamento_id' => 8,  'nombre' => 'SAN JOSÉ VILLANUEVA',         'activo' => true],
            ['id' => 145, 'departamento_id' => 8,  'nombre' => 'SAN MATÍAS',                  'activo' => true],
            ['id' => 146, 'departamento_id' => 8,  'nombre' => 'SAN PABLO TACACHICO',         'activo' => true],
            ['id' => 147, 'departamento_id' => 8,  'nombre' => 'TALNIQUE',                    'activo' => true],
            ['id' => 148, 'departamento_id' => 8,  'nombre' => 'TAMANIQUE',                   'activo' => true],
            ['id' => 149, 'departamento_id' => 8,  'nombre' => 'TEOTEPEQUE',                  'activo' => true],
            ['id' => 150, 'departamento_id' => 8,  'nombre' => 'TEPECOYO',                    'activo' => true],
            ['id' => 151, 'departamento_id' => 8,  'nombre' => 'ZARAGOZA',                    'activo' => true],
            // CHALATENANGO (dep 9)
            ['id' => 152, 'departamento_id' => 9,  'nombre' => 'AGUA CALIENTE',               'activo' => true],
            ['id' => 153, 'departamento_id' => 9,  'nombre' => 'ARCATAO',                     'activo' => true],
            ['id' => 154, 'departamento_id' => 9,  'nombre' => 'AZACUALPA',                   'activo' => true],
            ['id' => 155, 'departamento_id' => 9,  'nombre' => 'CANCASQUE',                   'activo' => true],
            ['id' => 156, 'departamento_id' => 9,  'nombre' => 'CHALATENANGO',                'activo' => true],
            ['id' => 157, 'departamento_id' => 9,  'nombre' => 'CITALÁ',                      'activo' => true],
            ['id' => 158, 'departamento_id' => 9,  'nombre' => 'COMAPALA',                    'activo' => true],
            ['id' => 159, 'departamento_id' => 9,  'nombre' => 'CONCEPCIÓN QUEZALTEPEQUE',    'activo' => true],
            ['id' => 160, 'departamento_id' => 9,  'nombre' => 'DULCE NOMBRE DE MARÍA',       'activo' => true],
            ['id' => 161, 'departamento_id' => 9,  'nombre' => 'EL CARRIZAL',                 'activo' => true],
            ['id' => 162, 'departamento_id' => 9,  'nombre' => 'EL PARAÍSO',                  'activo' => true],
            ['id' => 163, 'departamento_id' => 9,  'nombre' => 'LA LAGUNA',                   'activo' => true],
            ['id' => 164, 'departamento_id' => 9,  'nombre' => 'LA PALMA',                    'activo' => true],
            ['id' => 165, 'departamento_id' => 9,  'nombre' => 'LA REINA',                    'activo' => true],
            ['id' => 166, 'departamento_id' => 9,  'nombre' => 'LAS VUELTAS',                 'activo' => true],
            ['id' => 167, 'departamento_id' => 9,  'nombre' => 'NUEVA CONCEPCIÓN',            'activo' => true],
            ['id' => 168, 'departamento_id' => 9,  'nombre' => 'NUEVA TRINIDAD',              'activo' => true],
            ['id' => 169, 'departamento_id' => 9,  'nombre' => 'NOMBRE DE JESÚS',             'activo' => true],
            ['id' => 170, 'departamento_id' => 9,  'nombre' => 'OJOS DE AGUA',                'activo' => true],
            ['id' => 171, 'departamento_id' => 9,  'nombre' => 'POTONICO',                    'activo' => true],
            ['id' => 172, 'departamento_id' => 9,  'nombre' => 'SAN ANTONIO DE LA CRUZ',      'activo' => true],
            ['id' => 173, 'departamento_id' => 9,  'nombre' => 'SAN ANTONIO LOS RANCHOS',     'activo' => true],
            ['id' => 174, 'departamento_id' => 9,  'nombre' => 'SAN FERNANDO',                'activo' => true],
            ['id' => 175, 'departamento_id' => 9,  'nombre' => 'SAN FRANCISCO LEMPA',         'activo' => true],
            ['id' => 176, 'departamento_id' => 9,  'nombre' => 'SAN FRANCISCO MORAZÁN',       'activo' => true],
            ['id' => 177, 'departamento_id' => 9,  'nombre' => 'SAN IGNACIO',                 'activo' => true],
            ['id' => 178, 'departamento_id' => 9,  'nombre' => 'SAN ISIDRO LABRADOR',         'activo' => true],
            ['id' => 179, 'departamento_id' => 9,  'nombre' => 'LAS FLORES',                  'activo' => true],
            ['id' => 180, 'departamento_id' => 9,  'nombre' => 'SAN LUIS DEL CARMEN',         'activo' => true],
            ['id' => 181, 'departamento_id' => 9,  'nombre' => 'SAN MIGUEL DE MERCEDES',      'activo' => true],
            ['id' => 182, 'departamento_id' => 9,  'nombre' => 'SAN RAFAEL',                  'activo' => true],
            ['id' => 183, 'departamento_id' => 9,  'nombre' => 'SANTA RITA',                  'activo' => true],
            ['id' => 184, 'departamento_id' => 9,  'nombre' => 'TEJUTLA',                     'activo' => true],
            // CUSCATLÁN (dep 10)
            ['id' => 185, 'departamento_id' => 10, 'nombre' => 'COJUTEPEQUE',                 'activo' => true],
            ['id' => 186, 'departamento_id' => 10, 'nombre' => 'CANDELARIA',                  'activo' => true],
            ['id' => 187, 'departamento_id' => 10, 'nombre' => 'EL CARMEN',                   'activo' => true],
            ['id' => 188, 'departamento_id' => 10, 'nombre' => 'EL ROSARIO',                  'activo' => true],
            ['id' => 189, 'departamento_id' => 10, 'nombre' => 'MONTE SAN JUAN',              'activo' => true],
            ['id' => 190, 'departamento_id' => 10, 'nombre' => 'ORATORIO DE CONCEPCIÓN',      'activo' => true],
            ['id' => 191, 'departamento_id' => 10, 'nombre' => 'SAN BARTOLOMÉ PERULAPÍA',     'activo' => true],
            ['id' => 192, 'departamento_id' => 10, 'nombre' => 'SAN CRISTÓBAL',               'activo' => true],
            ['id' => 193, 'departamento_id' => 10, 'nombre' => 'SAN JOSÉ GUAYABAL',           'activo' => true],
            ['id' => 194, 'departamento_id' => 10, 'nombre' => 'SAN PEDRO PERULAPÁN',         'activo' => true],
            ['id' => 195, 'departamento_id' => 10, 'nombre' => 'SAN RAFAEL CEDROS',           'activo' => true],
            ['id' => 196, 'departamento_id' => 10, 'nombre' => 'SAN RAMÓN',                   'activo' => true],
            ['id' => 197, 'departamento_id' => 10, 'nombre' => 'SANTA CRUZ ANALQUITO',        'activo' => true],
            ['id' => 198, 'departamento_id' => 10, 'nombre' => 'SANTA CRUZ MICHAPA',          'activo' => true],
            ['id' => 199, 'departamento_id' => 10, 'nombre' => 'SUCHITOTO',                   'activo' => true],
            ['id' => 200, 'departamento_id' => 10, 'nombre' => 'TENANCINGO',                  'activo' => true],
            // SAN SALVADOR (dep 11)
            ['id' => 201, 'departamento_id' => 11, 'nombre' => 'AGUILARES',                   'activo' => true],
            ['id' => 202, 'departamento_id' => 11, 'nombre' => 'APOPA',                       'activo' => true],
            ['id' => 203, 'departamento_id' => 11, 'nombre' => 'AYUTUXTEPEQUE',               'activo' => true],
            ['id' => 204, 'departamento_id' => 11, 'nombre' => 'CUSCATANCINGO',               'activo' => true],
            ['id' => 205, 'departamento_id' => 11, 'nombre' => 'CIUDAD DELGADO',              'activo' => true],
            ['id' => 206, 'departamento_id' => 11, 'nombre' => 'EL PAISNAL',                  'activo' => true],
            ['id' => 207, 'departamento_id' => 11, 'nombre' => 'GUAZAPA',                     'activo' => true],
            ['id' => 208, 'departamento_id' => 11, 'nombre' => 'ILOPANGO',                    'activo' => true],
            ['id' => 209, 'departamento_id' => 11, 'nombre' => 'MEJICANOS',                   'activo' => true],
            ['id' => 210, 'departamento_id' => 11, 'nombre' => 'NEJAPA',                      'activo' => true],
            ['id' => 211, 'departamento_id' => 11, 'nombre' => 'PANCHIMALCO',                 'activo' => true],
            ['id' => 212, 'departamento_id' => 11, 'nombre' => 'ROSARIO DE MORA',             'activo' => true],
            ['id' => 213, 'departamento_id' => 11, 'nombre' => 'SAN MARCOS',                  'activo' => true],
            ['id' => 214, 'departamento_id' => 11, 'nombre' => 'SAN MARTÍN',                  'activo' => true],
            ['id' => 215, 'departamento_id' => 11, 'nombre' => 'SAN SALVADOR',                'activo' => true],
            ['id' => 216, 'departamento_id' => 11, 'nombre' => 'SANTIAGO TEXACUANGOS',        'activo' => true],
            ['id' => 217, 'departamento_id' => 11, 'nombre' => 'SANTO TOMÁS',                 'activo' => true],
            ['id' => 218, 'departamento_id' => 11, 'nombre' => 'SOYAPANGO',                   'activo' => true],
            ['id' => 219, 'departamento_id' => 11, 'nombre' => 'TONACATEPEQUE',               'activo' => true],
            // LA PAZ (dep 12)
            ['id' => 220, 'departamento_id' => 12, 'nombre' => 'ZACATECOLUCA',                'activo' => true],
            ['id' => 221, 'departamento_id' => 12, 'nombre' => 'CUYULTITÁN',                  'activo' => true],
            ['id' => 222, 'departamento_id' => 12, 'nombre' => 'EL ROSARIO',                  'activo' => true],
            ['id' => 223, 'departamento_id' => 12, 'nombre' => 'JERUSALÉN',                   'activo' => true],
            ['id' => 224, 'departamento_id' => 12, 'nombre' => 'MERCEDES LA CEIBA',           'activo' => true],
            ['id' => 225, 'departamento_id' => 12, 'nombre' => 'OLOCUILTA',                   'activo' => true],
            ['id' => 226, 'departamento_id' => 12, 'nombre' => 'PARAÍSO DE OSORIO',           'activo' => true],
            ['id' => 227, 'departamento_id' => 12, 'nombre' => 'SAN ANTONIO MASAHUAT',        'activo' => true],
            ['id' => 228, 'departamento_id' => 12, 'nombre' => 'SAN EMIGDIO',                 'activo' => true],
            ['id' => 229, 'departamento_id' => 12, 'nombre' => 'SAN FRANCISCO CHINAMECA',     'activo' => true],
            ['id' => 230, 'departamento_id' => 12, 'nombre' => 'SAN PEDRO MASAHUAT',          'activo' => true],
            ['id' => 231, 'departamento_id' => 12, 'nombre' => 'SAN JUAN NONUALCO',           'activo' => true],
            ['id' => 232, 'departamento_id' => 12, 'nombre' => 'SAN JUAN TALPA',              'activo' => true],
            ['id' => 233, 'departamento_id' => 12, 'nombre' => 'SAN JUAN TEPEZONTES',         'activo' => true],
            ['id' => 234, 'departamento_id' => 12, 'nombre' => 'SAN LUIS LA HERRADURA',       'activo' => true],
            ['id' => 235, 'departamento_id' => 12, 'nombre' => 'SAN LUIS TALPA',              'activo' => true],
            ['id' => 236, 'departamento_id' => 12, 'nombre' => 'SAN MIGUEL TEPEZONTES',       'activo' => true],
            ['id' => 237, 'departamento_id' => 12, 'nombre' => 'SAN PEDRO NONUALCO',          'activo' => true],
            ['id' => 238, 'departamento_id' => 12, 'nombre' => 'SAN RAFAEL OBRAJUELO',        'activo' => true],
            ['id' => 239, 'departamento_id' => 12, 'nombre' => 'SANTA MARÍA OSTUMA',          'activo' => true],
            ['id' => 240, 'departamento_id' => 12, 'nombre' => 'SANTIAGO NONUALCO',           'activo' => true],
            ['id' => 241, 'departamento_id' => 12, 'nombre' => 'TAPALHUACA',                  'activo' => true],
            // CABAÑAS (dep 13)
            ['id' => 242, 'departamento_id' => 13, 'nombre' => 'CINQUERA',                    'activo' => true],
            ['id' => 243, 'departamento_id' => 13, 'nombre' => 'DOLORES',                     'activo' => true],
            ['id' => 244, 'departamento_id' => 13, 'nombre' => 'GUACOTECTI',                  'activo' => true],
            ['id' => 245, 'departamento_id' => 13, 'nombre' => 'ILOBASCO',                    'activo' => true],
            ['id' => 246, 'departamento_id' => 13, 'nombre' => 'JUTIAPA',                     'activo' => true],
            ['id' => 247, 'departamento_id' => 13, 'nombre' => 'SAN ISIDRO',                  'activo' => true],
            ['id' => 248, 'departamento_id' => 13, 'nombre' => 'SENSUNTEPEQUE',               'activo' => true],
            ['id' => 249, 'departamento_id' => 13, 'nombre' => 'TEJUTEPEQUE',                 'activo' => true],
            ['id' => 250, 'departamento_id' => 13, 'nombre' => 'VICTORIA',                    'activo' => true],
            // SAN VICENTE (dep 14)
            ['id' => 251, 'departamento_id' => 14, 'nombre' => 'APASTEPEQUE',                 'activo' => true],
            ['id' => 252, 'departamento_id' => 14, 'nombre' => 'GUADALUPE',                   'activo' => true],
            ['id' => 253, 'departamento_id' => 14, 'nombre' => 'SAN CAYETANO ISTEPEQUE',      'activo' => true],
            ['id' => 254, 'departamento_id' => 14, 'nombre' => 'SAN ESTEBAN CATARINA',        'activo' => true],
            ['id' => 255, 'departamento_id' => 14, 'nombre' => 'SAN ILDEFONSO',               'activo' => true],
            ['id' => 256, 'departamento_id' => 14, 'nombre' => 'SAN LORENZO',                 'activo' => true],
            ['id' => 257, 'departamento_id' => 14, 'nombre' => 'SAN SEBASTIÁN',               'activo' => true],
            ['id' => 258, 'departamento_id' => 14, 'nombre' => 'SAN VICENTE',                 'activo' => true],
            ['id' => 259, 'departamento_id' => 14, 'nombre' => 'SANTA CLARA',                 'activo' => true],
            ['id' => 260, 'departamento_id' => 14, 'nombre' => 'SANTO DOMINGO',               'activo' => true],
            ['id' => 261, 'departamento_id' => 14, 'nombre' => 'TECOLUCA',                    'activo' => true],
            ['id' => 262, 'departamento_id' => 14, 'nombre' => 'TEPETITÁN',                   'activo' => true],
            ['id' => 263, 'departamento_id' => 14, 'nombre' => 'VERAPAZ',                     'activo' => true],
        ]);
    }
}
