<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProveedoresSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('proveedores')->insertOrIgnore([
            ['id' => 1,  'municipio_id' => 213, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 2, 'nombre_comercial' => 'UNO EL SALVADOR',                              'nombre' => 'UNO EL SALVADOR, S.A. DE C.V.',                    'apellido' => 'LEOBARDO LOPEZ',              'direccion' => 'EDIFICIO FUSADES, SANTA ELENA',                                           'dui' => null,          'nit' => '0614-040460-001-5', 'nrc' => '14-3',      'tipo_persona' => 2, 'activo' => true],
            ['id' => 2,  'municipio_id' => 213, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 2, 'nombre_comercial' => 'CENTRO DE SERVICIO DOÑO, S.A DE C.V.',          'nombre' => 'CENTRO DE SERVICIO DOÑO, S.A. DE C.V.',            'apellido' => 'SR. VICENTE DOÑO',            'direccion' => 'BLVD VENEZUELA',                                                          'dui' => null,          'nit' => '0614-011012-002-5', 'nrc' => '0002-3',    'tipo_persona' => 2, 'activo' => true],
            ['id' => 3,  'municipio_id' => 213, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 2, 'nombre_comercial' => 'TALLER DIDEA, S.A. DE C.V.',                   'nombre' => 'TALLER DIDEA, S.A. DE C.V.',                       'apellido' => 'LIC. ARNULFO FLORES',         'direccion' => 'CALLE SISIMILES, FRENTE A METROCENTRO',                                   'dui' => null,          'nit' => '1324-55559-393-9', 'nrc' => '9392-1',    'tipo_persona' => 2, 'activo' => true],
            ['id' => 4,  'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 4, 'nombre_comercial' => 'MENENDEZ MORENO S.A DE C.V.',                  'nombre' => 'MENEDEZ MORENO S.A DE C.V.',                       'apellido' => 'DAYSI DELMY MORENO DE MENENDEZ', 'direccion' => 'FINAL COLONIA AMERICA, CARRETERA A SAN MARCOS KM 3 1/2',               'dui' => null,          'nit' => '0614-080909-102-1', 'nrc' => '019605-4',  'tipo_persona' => 2, 'activo' => true],
            ['id' => 5,  'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 4, 'nombre_comercial' => 'MULTISERVICIOS A&M S.A. DE C.V.',              'nombre' => 'MULTISERVICIOS A&M S.A. DE C.V.',                  'apellido' => 'ERICK GILBERTO ARIAS MARTINEZ', 'direccion' => '29 CALLE PONIENTE NO 917, COLONIA LAYCO',                               'dui' => null,          'nit' => '0614-080909-102-1', 'nrc' => '019605-4',  'tipo_persona' => 2, 'activo' => true],
            ['id' => 6,  'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 1, 'nombre_comercial' => 'GOLDEN WILL INDUSTRIAL LIMITED, S.A. DE C.V.', 'nombre' => 'GOLDEN WILL INDUSTRIAL LIMITED, S.A. DE C.V.',     'apellido' => 'BO YANG',                     'direccion' => '4ª CALLE PONIENTE Y 23 AVENIDA SUR',                                      'dui' => null,          'nit' => '0614-261103-103-4', 'nrc' => '52999-0',   'tipo_persona' => 2, 'activo' => true],
            ['id' => 7,  'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 2, 'nombre_comercial' => 'GRUPO Q EL SALVADOR S.A. DE C.V.',             'nombre' => 'GRUPO Q EL SALVADOR S.A. DE C.V.',                 'apellido' => 'BLANCA VILMA ESQUIVEL GARCIA', 'direccion' => 'BOULEVARD LOS PROCERES Y AVENIDA LAS AMAPOLAS, COLONIA SAN MATEO',       'dui' => null,          'nit' => '1217-130688-001-0', 'nrc' => '579-7',     'tipo_persona' => 2, 'activo' => true],
            ['id' => 8,  'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 1, 'nombre_comercial' => 'TRANSPORTES EJECUTIVOS SHALOM',               'nombre' => 'TREJESH SA DE CV',                                 'apellido' => 'REINALDO GUZMAN RUIZ',        'direccion' => 'COLONIA FLOR BLANCA, EDIFICIO INSTEL LOCAL NO 8',                         'dui' => null,          'nit' => '0614-140312-104-0', 'nrc' => '215734-2',  'tipo_persona' => 2, 'activo' => true],
            ['id' => 9,  'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 1, 'nombre_comercial' => 'ESTRUCTURAS METALICAS Y CONSTRUCCIONES S.A. DE C.V.', 'nombre' => 'ESTRUCONS SA DE CV',                               'apellido' => 'CESAR EDUARDO FLANDES RODAS', 'direccion' => '29 AVENIDA SUR Y ANTIGUA CALLE DEL FERROCARRIL NO 1533',                 'dui' => null,          'nit' => '0614-150390-103-4', 'nrc' => '41115-9',   'tipo_persona' => 2, 'activo' => true],
            ['id' => 10, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 1, 'nombre_comercial' => 'SUREMOTO',                                     'nombre' => 'JOSE ROBERTO',                                     'apellido' => 'CORNEJO MOLINA',              'direccion' => 'ALAMEDA ROOSEVELT, COLONIA FLOR BLANCA EDIFICIO 1921',                    'dui' => '02446984-4', 'nit' => '0614-020383-103-8', 'nrc' => '208776-7',  'tipo_persona' => 1, 'activo' => true],
            ['id' => 11, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 4, 'nombre_comercial' => 'CONFORT TRANSPORTE-LINEA EJECUTIVA',           'nombre' => 'RONALD ALEXANDER',                                 'apellido' => 'CRUZ SORIANO',                'direccion' => 'BOULEVARD CONSTITUCION Y PROLONGACION ALAMEDA JUAN PABLO II #1',          'dui' => '02060107-0', 'nit' => '1121-220383-101-2', 'nrc' => '252218-1',  'tipo_persona' => 1, 'activo' => true],
            ['id' => 12, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 4, 'nombre_comercial' => 'GIBSON CIA. SUCESORES, S.A. DE C.V.',          'nombre' => 'JOSIAS ENRIQUE',                                   'apellido' => 'MEDRANO MEDRANO',             'direccion' => '17 CALLE PONIENTE NO. 320, SAN SALVADOR',                                 'dui' => '00000000-0', 'nit' => '0614-200154-001-4', 'nrc' => '37427',     'tipo_persona' => 1, 'activo' => true],
            ['id' => 13, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 2, 'nombre_comercial' => 'SEGUROS FEDECREDITO, S.A.',                    'nombre' => 'SEGUROS FEDECREDITO, S.A.',                        'apellido' => 'XXX',                         'direccion' => 'XXX',                                                                     'dui' => null,          'nit' => '0000-000000-000-0', 'nrc' => '00000-0',   'tipo_persona' => 2, 'activo' => true],
            ['id' => 14, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 1, 'nombre_comercial' => 'REPUESTOLANDIA',                               'nombre' => 'REPUESTOLANDIA, S.A. DE C.V.',                     'apellido' => 'HELIA DEL CARMEN MARIA PADILLA PINO', 'direccion' => '29 AV. SUR Y 12 CALLE PONIENTE, COL. CUCUMACAYAN #1540',            'dui' => null,          'nit' => '0614-251010-102-3', 'nrc' => '205019-3',  'tipo_persona' => 2, 'activo' => true],
            ['id' => 15, 'municipio_id' => 130, 'actividad_economica_id' => 3, 'tamano_proveedor_id' => 4, 'nombre_comercial' => 'RENT A CARS LINEA ROSA S.A. DE C.V.',          'nombre' => 'RENT A CARS LINEA ROSA S.A. DE C.V.',              'apellido' => 'MEYBI LORENA GONZALEZ',       'direccion' => 'ANTIGUO CUSCATLAN, LA LIBERTAD',                                          'dui' => null,          'nit' => '0614-241114-106-4', 'nrc' => '15653146',  'tipo_persona' => 2, 'activo' => true],
            ['id' => 17, 'municipio_id' => 23,  'actividad_economica_id' => 1, 'tamano_proveedor_id' => 4, 'nombre_comercial' => 'IMPORTADORA RAMIREZ, S.A. DE C.V.',            'nombre' => 'IMPORTADORA RAMIREZ, S.A. DE C.V.',                'apellido' => 'MARIO ERNESTO RAMIREZ PERAZA', 'direccion' => 'KM 75 CART. PANAMERICANA, CANTON LOS AMATES',                            'dui' => null,          'nit' => '0614-300992-106-8', 'nrc' => '713007',    'tipo_persona' => 2, 'activo' => true],
            ['id' => 18, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 1, 'nombre_comercial' => 'SERVICIO AUTOMOTRIZ ESPAÑA S.A. DE C.V.',      'nombre' => 'MANTENIMIENTO DE VEHÍCULOS AUTOMOTORES',           'apellido' => 'LIC PEDRO OWALDO PEREZ MATÍNEZ', 'direccion' => 'AV. ESPAÑA Y 25 CALLE ORIENTE N°1406 BARRIO SAN MIGUELITO',           'dui' => null,          'nit' => '0614-612111-105-5', 'nrc' => '215213-6',  'tipo_persona' => 2, 'activo' => true],
            ['id' => 19, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 4, 'nombre_comercial' => 'R.NUÑEZ S.A DE C.V',                          'nombre' => 'RIVERA NUÑEZ S.A DE C.V',                          'apellido' => 'JOSE ROBERTO RIOS ANDRADE',   'direccion' => 'BULEVAR VENEZUELA # 2965 SAN SALVADOR',                                   'dui' => null,          'nit' => '0903-050348-001-7', 'nrc' => '5202-7',    'tipo_persona' => 2, 'activo' => true],
            ['id' => 20, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 2, 'nombre_comercial' => 'VERSATEC',                                     'nombre' => 'VERSATEC S.A, DE C.V',                             'apellido' => 'JOSE RIVERA ESCOBAR',         'direccion' => 'COLONIA SAN BENITO, EDIFICIO CENTURY TOWER, EL SALVADOR',                 'dui' => null,          'nit' => '0614-290807-105-1', 'nrc' => 'N° 181282-8', 'tipo_persona' => 2, 'activo' => true],
            ['id' => 21, 'municipio_id' => 215, 'actividad_economica_id' => 1, 'tamano_proveedor_id' => 2, 'nombre_comercial' => 'DIPARVEL, S.A. DE C.V.',                       'nombre' => 'DISTRIBUIDORA PAREDES VELA',                       'apellido' => 'CLAUDIA MARIA PAREDES VELA',  'direccion' => '29 CALLE PONIENTE',                                                       'dui' => null,          'nit' => '1217-160992-101-8', 'nrc' => '70622-1',   'tipo_persona' => 2, 'activo' => true],
        ]);
    }
}