/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare let self: ServiceWorkerGlobalScope

// Auto-clean old caches
cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Take control immediately
self.skipWaiting()
clientsClaim()

// ─── MANEJADOR DE CLIC EN NOTIFICACIONES ────────────────────────────────────────

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // Recuperar la URL del campo 'data' o usar la raíz como fallback
  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // 1. Intentar encontrar una pestaña que ya tenga esta URL abierta
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      
      // 2. Si no hay pestaña abierta, intentar enfocar cualquiera y navegar, o abrir nueva
      if (clientList.length > 0) {
        let client = clientList[0];
        for (const c of clientList) {
          if (c.focused) {
            client = c;
            break;
          }
        }
        return client.navigate(urlToOpen).then(c => c?.focus());
      }
      
      // 3. Como último recurso, abrir una nueva ventana
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
