/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare let self: ServiceWorkerGlobalScope

// Auto-clean old caches
cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Take control immediately
self.skipWaiting()
clientsClaim()

// ─── MANEJADOR DE EVENTO PUSH VAPID ─────────────────────────────────────────────

self.addEventListener('push', (event) => {
  let payload: any = {}

  try {
    payload = event.data ? event.data.json() : {}
  } catch {
    payload = { title: 'Notificación de Transporte', body: event.data ? event.data.text() : '' }
  }

  const title = payload.title || payload.titulo || 'Notificación Sistema de Transporte'
  const options = {
    body: payload.body || payload.mensaje || 'Tienes una nueva actualización de tu solicitud.',
    icon: payload.icon || '/icon-192x192.png',
    badge: payload.badge || '/icon-192x192.png',
    data: {
      url: payload.data?.url || payload.url || '/'
    }
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

// ─── MANEJADOR DE CLIC EN NOTIFICACIONES ────────────────────────────────────────


self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // 1. Normalizar la URL (Convertir relativa a absoluta)
  const relativeUrl = event.notification.data?.url || '/';
  const urlToOpen = new URL(relativeUrl, self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // 2. Intentar encontrar una pestaña que ya tenga esta URL exacta abierta
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      
      // 3. Si no hay una con la URL exacta, intentar enfocar la primera pestaña disponible del origen
      // y navegar esa pestaña a la nueva URL.
      if (clientList.length > 0) {
        let clientToUse = clientList[0];
        // Preferir la que ya esté enfocada si es posible
        for (const c of clientList) {
          if (c.focused) {
            clientToUse = c;
            break;
          }
        }
        return clientToUse.navigate(urlToOpen).then(c => c?.focus());
      }
      
      // 4. Si no hay ninguna pestaña abierta de la App, abrir una nueva
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
